name: issue-agent_refine
description: |
  【用途】
  トリアージ（優先順位付け）を行う前に、作成されたばかりの Issue の内容を精査・洗練させます。
  不明瞭なレポートや情報不足な報告を構造化し、Issueの品質を向上させます。

  【利用タイミング】
   - 外部ユーザーやQAチームから報告された Issue。
   - 内容が曖昧な Issue。
   - トリアージ担当や解析エージェントに割り当てる前の「下地作り」として。

  【主な振る舞い】
   - Issue の解析: タイトルと本文を読み解きます。
   - 不足情報の特定: 再現手順、実行環境、期待される結果と実際の結果などの欠落をチェックします。
   - フォーマットの整形: 内容を構造化されたテンプレートに書き換えます。
   - 不足への対応: 情報が不十分な場合、ピンポイントで質問をコメントとして投稿します。

  【出力イメージ】
   - 構造化されたセクション:
     - 概要
     - 再現手順
     - 期待される結果
     - 実際の結果
     - 実行環境
   - 情報の追記リクエスト:
     - 不足している重要な詳細がある場合のコメント

  【コスト方針】
   - 低コストなモデル（gpt-4o-mini）を使用し、頻繁に実行することを想定。
   - 高度な推論よりも、明快さとスピードを重視。

  【ルール】
   - ラベルの付与は行わない。
   - 担当者の変更は行わない。
   - 内容の整理と、不明点の質問のみを行う。

model: gpt-4o-mini
capabilities:
  - issue_refinement
  - text_structuring
  - clarification_request
