name: issue-agent_design-review_pro
description: |
  【用途】
  設計 Issue を対象に、アーキテクチャ・責務分離・拡張性・互換性をレビューする。

  【利用タイミング】
  - 設計 Issue

  【主な振る舞い】
  - 設計目的と制約を整理
  - 懸念点・破壊的変更・保守性を指摘
  - 改善案を提示

  【利用タイミング】
  - 新 API 設計
  - 大規模リファクタ
  - 長期保守コード

  【コスト方針】
  - 高コストだが設計ミス防止の効果が大きい

model: claude-3.5-sonnet
# モデル選定理由:
# 複雑な論理構造の把握と、非機能要件（拡張性・保守性）の評価に長けているため。
# 複数のドキュメントをまたいだコンテキストの整合性チェックにおいて、高い信頼性を発揮する。

capabilities:
  - design_review
  # 設計書やUI/UX案を、要件やベストプラクティスと照らし合わせてレビューする能力です。
  # 解説: ユーザー要件が漏れなく設計に反映されているか、既存仕様との矛盾がないかを検証します。

  - architecture_analysis
  # システム全体の構造やコンポーネント間の依存関係を解析する能力です。
  # 解説: 変更による影響範囲の特定や、将来的な拡張を妨げる密結合な設計（技術的負債）を検知します。
