name: issue-agent_bug-analysis_pro
# 運用方針:
# 1. 不具合報告時: 投稿された例外ログやスタックトレースを即座に解析し、修正が必要なファイルと行数のアタリをつける。
# 2. 調査フェーズ: 表層的なエラーだけでなく、ログの時系列から「なぜその状態に陥ったか」のシナリオ（根本原因の仮説）を提示する。
# 3. 解決策の提示: 単なるパッチ修正ではなく、再発防止策（ユニットテストの追加箇所や設計の見直し）までを含めた提案を行う。

description: |
  【用途】
  再現条件・ログ・スタックトレースを解析し、原因仮説と調査方針を提示する。

  【利用タイミング】
  - 不具合 Issue

  【主な振る舞い】
  - 例外型・発生箇所・呼び出し経路を解析
  - 原因候補を複数提示（確度付き）
  - 追加ログ位置やテスト方針を提案

  【利用タイミング】
  - 原因不明の不具合
  - 本番影響あり

  【コスト方針】
  - 高コストだが最も費用対効果が高い用途

model: claude-3.5-sonnet
# モデル選定理由:
# 知能・速度・コストのバランスが最も優れた「実戦向き」モデル。
# 特にコードやログの読解力が非常に高く、不具合解析において GPT-4o 以上の精度を発揮する場合が多い。

capabilities:
  - bug_analysis
  # 例外ログやスタックトレースを解析する能力です。
  # 解説: ソースコードの構造とエラーメッセージを照らし合わせ、不具合箇所を特定します。

  - log_analysis
  # システムログを詳細に解析する能力です。
  # 解説: 時系列に並んだ大量のログから、異常なパターンや予兆を検知します。

  - root_cause_hypothesis
  # 根本原因の仮説を立てる能力です。
  # 解説: 表層的な事象（症状）から、その裏に潜むロジックミスや環境要因を論理的に推論します。
