name: issue-agent_design-review_pro
# 運用方針:
# 1. 設計・検討フェーズ: 要件定義（Issue）に対し、既存のアーキテクチャやドキュメントとの矛盾がないか、非機能要件（性能・拡張性）に懸念がないかを精査する。
# 2. 影響範囲の特定: 提案された変更が、他のサブシステムや将来の機能拡張にどのような波及効果（副作用）を及ぼすかを明示する。
# 3. 継続的な品質管理: 「とりあえずの実装」が技術的負債化する予兆を検知し、疎結合でメンテナンス性の高い構造への代替案を提示する。

description: |
  【用途】
  設計 Issue を対象に、アーキテクチャ・責務分離・拡張性・互換性をレビューする。

  【利用タイミング】
  - 設計 Issue

  【主な振る舞い】
  - 設計目的と制約を整理
  - 懸念点・破壊的変更・保守性を指摘
  - 改善案を提示

  【利用タイミング】
  - 新 API 設計
  - 大規模リファクタ
  - 長期保守コード

  【コスト方針】
  - 高コストだが設計ミス防止の効果が大きい

model: claude-3.5-sonnet
# モデル選定理由:
# 複雑な論理構造の把握と、非機能要件（拡張性・保守性）の評価に長けているため。
# 複数のドキュメントをまたいだコンテキストの整合性チェックにおいて、高い信頼性を発揮する。

capabilities:
  - design_review
  # 設計書やUI/UX案を、要件やベストプラクティスと照らし合わせてレビューする能力です。
  # 解説: ユーザー要件が漏れなく設計に反映されているか、既存仕様との矛盾がないかを検証します。

  - architecture_analysis
  # システム全体の構造やコンポーネント間の依存関係を解析する能力です。
  # 解説: 変更による影響範囲の特定や、将来的な拡張を妨げる密結合な設計（技術的負債）を検知します。
