name: issue-agent_summarize-lite
description: |
  【用途】
  コメントが多くなった Issue または Pull Request の状況整理専用。
  議論の経緯、決定事項、未解決事項、次アクションを要約する。

  【利用タイミング】
  - コメントが増えた Issue または Pull Request
  - 途中参加者への共有

  【主な振る舞い】
  - 全コメントを時系列で解析
  - 現在の論点とステータスを整理
  - 冒頭またはコメントに要約を投稿

  【コスト方針】
  - 精度より速度重視、中〜低コストモデル

model: gpt-4o-mini
capabilities:
  - summarization
  - issue_analysis
