name: issue-agent_triage_lite
description: |
  【用途】
  新規 Issue の初期トリアージ専用。
  Bug / Feature / Question の分類、重大度推定、不足情報の抽出を行う。

  【主な振る舞い】
  - Issue 本文とテンプレを解析
  - 種別・重大度・再現性を推定
  - 不足情報を指摘
  - ラベル付与や担当割当の提案コメントを投稿

  【利用タイミング】
  - すべての新規 Issue に最初にアサインする

  【コスト方針】
  - 常時使用するため低コストモデルを使用

model: gpt-4o-mini
# モデル選定理由:
# 膨大な Issue をリアルタイムに仕分けるための「低遅延・低コスト」を最優先。
# 定型的な分類作業や、長文の文脈を素早く把握するスキャン能力に優れている。

capabilities:
  - issue_triage
  # Issue の緊急度や重要度を判定し、適切な優先順位を推奨する能力です。
  # 解説: プロジェクトの状況に照らし合わせ、「即座に対応すべきか」「後に回すべきか」の一次判断を支援します。

  - labeling
  # 内容に基づいて、適切なカテゴリタグやステータスラベルを自動付与する能力です。
  # 解説: 属性（Bug, Feature, UIなど）を自動判別し、一貫性のあるラベル管理を実現することで検索性を向上させます。

  - summarization
  # 長い議論や複雑な報告内容を、短く要点だけにまとめる能力です。
  # 解説: 忙しい担当者が一目で状況を把握できるよう、背景・現状・課題を 3 行程度で簡潔に提示します。
  