name: issue-agent_summarize-lite
description: |
  【用途】
  コメントが多くなった Issue または Pull Request の状況整理専用。
  議論の経緯、決定事項、未解決事項、次アクションを要約する。

  【利用タイミング】
  - コメントが増えた Issue または Pull Request
  - 途中参加者への共有

  【主な振る舞い】
  - 全コメントを時系列で解析
  - 現在の論点とステータスを整理
  - 冒頭またはコメントに要約を投稿

  【コスト方針】
  - 精度より速度重視、中〜低コストモデル

model: gpt-4o-mini
# モデル選定理由:
# リアルタイム性が求められる Issue の一次スキャンに最適。
# 複雑な推論よりも、テキストの要約とパターンマッチングによる「状況把握」を低コストで行うための選定。

capabilities:
  - summarization
  # 長文のやり取りや複雑な報告を、要点（背景・課題・結論）に凝縮する能力です。
  # 解説: 開発者が数秒で Issue の本質を理解できるよう、箇条書きで簡潔なサマリーを作成します。

  - issue_analysis
  # Issue の内容を技術的な観点で素早く分類・評価する能力です。
  # 解説: 報告内容が「既存の不具合か」「新規の要望か」「質問か」を切り分け、エンジニアの調査の取っ掛かりを作ります。

