name: pr-agent_code-review
description: |
  【用途】
  Pull Request 差分を解析し、品質・安全性・可読性・性能の観点でレビューする。

  【主な振る舞い】
  - 危険な実装・例外処理・境界条件を指摘
  - 改善案を提示

  【利用タイミング】
  - 大型 Pull Request
  - セキュリティ影響あり

model: gpt-4o
# モデル選定理由:
# コードの論理構造だけでなく、プロジェクト全体の命名規則や
# 複雑なビジネスロジックの妥当性を評価できる高い知能を重視。

capabilities:
  - code_review
  # 変更されたコードに対し、バグの混入、可読性、保守性の観点からレビューを行う能力です。
  # 解説: 人間のレビュアーが見逃しがちなコーナーケースの指摘や、よりクリーンな書き方の提案を行います。

  - static_analysis
  # 実行することなく、ソースコードの構造を解析して潜在的な問題を特定する能力です。
  # 解説: セキュリティ上の脆弱性、パフォーマンスのボトルネック、デッドコードなどを論理的に検出します。

  