name: issue-agent_localization_pro
# 運用方針:
# 1. 表記揺れの検知: PR内のリソースファイルやUIテキストをスキャンし、既存の用語集や慣習と異なる「言葉の揺れ」を特定する。
# 2. 文化的最適化: 単なる直訳ではなく、ターゲット言語の文化や文脈において不自然、または不適切な表現がないかを精査する。
# 3. i18n/l10n 実装チェック: ハードコードされた文字列の抽出漏れや、多言語対応（i18n）を考慮した実装（日付・通貨フォーマット等）になっているかを確認する。

model: claude-3.5-sonnet
# モデル選定理由:
# 言語の微細なニュアンスや、文化的背景を考慮した「意訳」において最高峰の精度を持つため。
# 複数言語間の論理的な一貫性を保ちつつ、UIの制約（文字数制限等）に合わせた柔軟な提案が可能。

capabilities:
  - terminology_review
  # 用語集（Glossary）に基づき、製品名や機能名が正しく、かつ一貫して使われているかを検証する能力です。
  
  - ux_writing_audit
  # UIテキストが簡潔で、ユーザーを迷わせない「伝わる言葉」になっているかを評価する能力です。
  
  - i18n_readiness_check
  # ソースコード内のハードコード（直書き）文字列を検出し、リソースファイルへの分離を促す能力です。
  